#!/usr/bin/env bash
#set -o errexit -o nounset -o pipefail

img="$(./bocker init ~/base-image | awk '{print $2}')"
./bocker images | grep -qw "$img"
[[ "$?" == 0 ]]

./bocker run "$img" ls testfile
ps="$(./bocker ps | grep 'ls testfile' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
sudo ./bocker rm "$ps"
[[ "$logs" == "ls: testfile: No such file or directory"* ]]

./bocker run "$img" touch testfile
ps="$(./bocker ps | grep 'touch testfile' | awk '{print $1}')"
./bocker commit "$ps" "$img"

./bocker run "$img" ls testfile
ps="$(./bocker ps | grep 'ls testfile' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
[[ "$logs" == 'testfile' ]]
